kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: alpine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        stdin: true
        tty: true
        image: dstroot/alpine:latest
        command: [ "/bin/sh" ]
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: ghost
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost
        gcePersistentDisk:
          pdName: ghost
          fsType: ext4
