apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
  # namespace: kube-system
spec:
  type: LoadBalancer   # LoadBalancer or NodePort
  ports:
  - port: 80
    targetPort: kibana
    protocol: TCP
  selector:
    app: kibana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  # namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
      # namespace: kube-system
    spec:
      containers:
      - name: kibana
        image: kibana:4.5.4
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - name: kibana
          containerPort: 5601
