apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  # - port: 80 # service port
  #   targetPort: 80  # port on container
  #   protocol: TCP
  - port: 443 # service port
    targetPort: 443  # port on container
    protocol: TCP
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dstroot/nginx:1.0.0
        resources:  # http://kubernetes.io/docs/user-guide/compute-resources/
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: TARGET_SERVICE
          value: prometheus:80
        - name: ENABLE_BASIC_AUTH
          value: "true"  # booleans and numbers must be quoted in env values
        - name: ENABLE_SSL
          value: "true"
        ports:
        # - name: http
        # - containerPort: 80
        # - name: https
        - containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: nginx-secrets
