apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 3306  # service port
    targetPort: mysql  # container port
  selector:
    app: mysql
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.14
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        gcePersistentDisk:
          pdName: mysql-disk
          fsType: ext4
