apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        # Uncomment below to allocate a tty if ever needed
        # stdin: true
        # tty: true
        image: wordpress
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        gcePersistentDisk:
          # This disk must already exist.
          pdName: wordpress-disk
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  type: LoadBalancer   # replace with LoadBalancer in prod, otherwise NodePort
  ports:
  - port: 80
    targetPort: wordpress
    protocol: TCP
  selector:
    app: wordpress
    tier: frontend
