kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-config
  namespace: default
data:
  vault.hcl: |
    backend "file" {
      path = "/vault/file"
    }

    listener "tcp" {
     address = "127.0.0.1:8200"
     tls_disable = 1
    }
