
apiVersion: v1
kind: ReplicationController
metadata:
  name: myadmin
  namespace: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - name: phpmyadmin
        image: nazarpc/phpmyadmin
        ports:
        - containerPort: 80
