apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: default
spec:
  type: LoadBalancer   # LoadBalancer or NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: explorer
  sessionAffinity: None
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: explorer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
      - name: explorer
        image: gcr.io/google_containers/explorer:1.0
        args:
        - -port=8080
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        # env:
        # - name: GF_SERVER_ROOT_URL
        #   value: http://grafana.server.name
        #   # Pass the plugins you want installed with the GF_INSTALL_PLUGINS
        #   # environment variable as a comma separated list.
        # - name: GF_INSTALL_PLUGINS
        #   value: "grafana-clock-panel,grafana-simple-json-datasource"
        # - name: GF_SECURITY_ADMIN_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: grafana-secret
        #       key: password
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /etc/prometheus
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: prometheus
      #
      #   volumeMounts:
      #   - name: authentication
      #     mountPath: /etc/secrets
      #     # readOnly: true
      # volumes:
      # - name: authentication
      #   secret:
      #     secretName: nginx-secret
