apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 130.211.126.76
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    app: explorer
  sessionAffinity: None
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: explorer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
      - name: explorer
        image: gcr.io/google_containers/explorer:1.0
        args:
        - -port=8080
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 25m
            memory: 25Mi
