apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost
data:
  config.js: |
    // Ghost Configuration
    // Documentation can be found at http://docs.ghost.org/usage/configuration/

    var path = require('path'),
        config;

    config = {
        production: {
            url: process.env.GHOST_URL,
            // forceAdminSSL: process.env.PROD_FORCE_ADMIN_SSL,
            mail: {
                transport: 'SMTP',
                options: {
                    service: process.env.MAIL_SERVICE,  // 'Gmail', 'SES', 'Mailgun'
                    // host: process.env.MAIL_HOST,
                    // secureConnection: process.env.MAIL_SSL,
                    // port: process.env.MAIL_PORT,
                    auth: {
                        user: process.env.MAIL_USERNAME,
                        pass: process.env.MAIL_PASSWORD,
                    },
                },
                from: process.env.MAIL_FROM
            },
            database: {
              client: process.env.DATABASE_TYPE,  // 'mysql' or 'pg'
              connection: {
                host     : process.env.DATABASE_HOST,
                user     : process.env.DATABASE_USER,
                password : process.env.DATABASE_PASS,
                database : process.env.DATABASE_DB,
                charset  : 'utf8'
              }
            },
            server: {
                host: '0.0.0.0',
                port: '2368'
            },
            paths: {
                contentPath: '/content'
            }
        },

        // standard ghost development configuration
        development: {
            url: 'http://localhost:2368',
            database: {
                client: 'sqlite3',
                connection: {
                    filename: path.join(__dirname, '/content/data/ghost-dev.db')
                },
                debug: false
            },
            server: {
                host: '127.0.0.1',
                port: '2368'
            },
            paths: {
                contentPath: path.join(__dirname, '/content/')
            }
        }
    };

    module.exports = config;
