apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  selector:
    app: gogs
  type: LoadBalancer
  ports:
  - port: 80 # service port
    targetPort: gogs  # port on container
    protocol: TCP
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      name: gogs
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: gogs/gogs:0.9.71
        # imagePullPolicy: Always
        # resources:  # http://kubernetes.io/docs/user-guide/compute-resources/
        #   requests:
        #     cpu: 100m
        #     memory: 500Mi
        ports:
        - name: gogs-ssh
          containerPort: 22
          protocol: TCP
        - name: gogs
          containerPort: 3000
          protocol: TCP
        env:
        - name: SOCAT_LINK
          value: "false"
        - name: RUN_CROND
          value: "true"
        volumeMounts:
        - name: gogs
          mountPath: /data
      volumes:
      - name: gogs
        gcePersistentDisk:
          pdName: gogs
          fsType: ext4
