apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  type: LoadBalancer
  ports:
  - port: 80  # service port
    targetPort: 8081 # container port
    # protocol: TCP
  selector:
    app: redis
    role: master
    tier: backend
