---
# A headless service to create DNS records
# From mariadb-0 do: ping mariadb-1.mariadb.mysql.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mariadb
  namespace: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 4444
    name: sst
  - port: 4567
    name: replication
  - protocol: UDP
    port: 4567
    name: replicationudp
  - port: 4568
    name: ist
  # [podname].mariadb.mysql.svc.cluster.local
  clusterIP: None
  selector:
    app: mariadb
